# Generated by Django 6.0.5 on 2026-06-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
