# Generated by Django 6.0.5 on 2026-06-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkingticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('ANY', 'Any Vehicle'), ('CAR', 'Car'), ('BIKE', 'Bike'), ('RICKSHAW', 'Rickshaw'), ('BUS', 'Bus')], db_index=True, default='ANY', max_length=20),
        ),
    ]
